spring.application.name=demo

# OTel Exporter Endpoint
otel.exporter.otlp.endpoint=http://otel-collector:4317
otel.exporter.otlp.protocol=grpc

# OTel Resource Attributes
otel.resource.attributes=service.name=springboot-app

# OTel Metrics Exporter
otel.metrics.exporter=otlp

# OTel Traces Exporter
otel.traces.exporter=otlp

# Spring Boot Actuator Endpoints - enable prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
