spring.application.name=demo

# OTel Exporter Endpoint - Force HTTP
otel.exporter.otlp.endpoint=http://localhost:4318
otel.exporter.otlp.protocol=http/protobuf
otel.exporter.otlp.traces.endpoint=http://localhost:4318
otel.exporter.otlp.metrics.endpoint=http://localhost:4318
otel.exporter.otlp.logs.endpoint=http://localhost:4318

# Disable gRPC
otel.exporter.otlp.traces.protocol=http/protobuf
otel.exporter.otlp.metrics.protocol=http/protobuf
otel.exporter.otlp.logs.protocol=http/protobuf

# OTel Resource Attributes
otel.resource.attributes=service.name=springboot-app

# OTel Metrics Exporter
otel.metrics.exporter=otlp

# OTel Exporter Timeouts and Retries
otel.exporter.otlp.timeout=100000
otel.exporter.otlp.retry.max-attempts=3
otel.exporter.otlp.retry.initial-interval=100000
otel.exporter.otlp.retry.max-interval=100000

# Enable Log Correlation and Code Attributes
otel.instrumentation.logs.capture-code-attributes=true
otel.instrumentation.log4j-appender.experimental-capture-mdc-attributes=*
otel.instrumentation.logback-appender.experimental-capture-mdc-attributes=*

# Spring Boot Actuator Endpoints - enable prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
